name: CI

on:
  push:
    branches:
      - "**"

jobs:
  php83:
    name: "php 8.3"
    runs-on: ubuntu-latest
    container: "nofutur3/php-tests:8.3"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install tools
        run: phive install --trust-gpg-keys E82B2FB314E9906E,4AA394086372C20A

      - name: Install dependencies
        run: composer install --no-interaction

      - name: Chesk code style
        run: tools/php-cs-fixer fix --dry-run --no-interaction

      - name: Run static analysis
        run: vendor/bin/phpstan analyse

      - name: Run tests
        run: tools/phpunit test/ --bootstrap vendor/autoload.php

  php83a:
    name: "php 8.3, laravel 10.0, validator 0.5"
    runs-on: ubuntu-latest
    container: "nofutur3/php-tests:8.3"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install tools
        run: phive install --trust-gpg-keys E82B2FB314E9906E,4AA394086372C20A

      - name: Install dependencies
        run: composer update --no-interaction --with simple-as-fuck/php-validator:^0.5.0 --with illuminate/contracts:^10.0

      - name: Run static analysis
        run: vendor/bin/phpstan analyse --configuration=phpstan-validator-0.5.neon.dist

      - name: Run tests
        run: tools/phpunit test/ --bootstrap vendor/autoload.php

  php82:
    name: "php 8.2"
    runs-on: ubuntu-latest
    container: "nofutur3/php-tests:8.2"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install tools
        run: phive install --trust-gpg-keys E82B2FB314E9906E,4AA394086372C20A

      - name: Install dependencies
        run: composer install --no-interaction

      - name: Run static analysis
        run: vendor/bin/phpstan analyse

      - name: Run tests
        run: tools/phpunit test/ --bootstrap vendor/autoload.php

  php81b:
    name: "php 8.1, validator 0.2"
    runs-on: ubuntu-latest
    container: "nofutur3/php-tests:8.1"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: composer update --no-interaction --with simple-as-fuck/php-validator:^0.2.0

      - name: Run static analysis
        run: vendor/bin/phpstan analyse

      - name: Run tests
        run: vendor/bin/phpunit test/

  php81c:
    name: "php 8.1, validator 0.3"
    runs-on: ubuntu-latest
    container: "nofutur3/php-tests:8.1"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: composer update --no-interaction --with simple-as-fuck/php-validator:^0.3.0

      - name: Run static analysis
        run: vendor/bin/phpstan analyse

      - name: Run tests
        run: vendor/bin/phpunit test/

  php81d:
    name: "php 8.1, validator 0.4, laravel 9.0, symfony 6.0"
    runs-on: ubuntu-latest
    container: "nofutur3/php-tests:8.1"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: composer update --no-interaction --with simple-as-fuck/php-validator:^0.4.0 --with illuminate/contracts:^9.0 --with symfony/lock:^6.0.7

      - name: Run static analysis
        run: vendor/bin/phpstan analyse

      - name: Run tests
        run: vendor/bin/phpunit test/

  php81a:
    name: "php 8.1, validator 0.1, laravel 8.0, symfony 5.3"
    runs-on: ubuntu-latest
    container: "nofutur3/php-tests:8.1"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: composer update --no-interaction --with simple-as-fuck/php-validator:^0.1.0 --with illuminate/contracts:^8.0 --with symfony/lock:^5.4.7

      - name: Run static analysis
        run: vendor/bin/phpstan analyse

      - name: Run tests
        run: vendor/bin/phpunit test/

  php81:
    name: "php 8.1"
    runs-on: ubuntu-latest
    container: "nofutur3/php-tests:8.1"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: composer install --no-interaction

      - name: Run static analysis
        run: vendor/bin/phpstan analyse

      - name: Run tests
        run: vendor/bin/phpunit test/
